### ISSUE TITLE
Joystick/Gamepad support...

### ISSUE THREAD

**Issue by DocMAX** [ehough/docker-kodi#16]
...can it be done?

**Comment by ehough** [comment]
I don't see any reason why it couldn't be done. [The documentation](https://kodi.wiki/view/Game_controllers) seems to indicate that no new software is needed for most controllers. So my guess is that the only task would be to make the host devices (`/dev`) available to the container. e.g. `-v /dev/input/joystick:/dev/input/joystick`

I have a PS4 controller as well as a classic NES controller (USB) that I'll start to test with.

Could you let me know which controller you have?

**Comment by DocMAX** [comment]
Sure, i have a Xbox 360 Wireless controller. I will test, too.

**Comment by ehough** [comment]
Great, thanks. If you find any relevant docs, guides, or how-to's related to getting this to work, please post them here and I'll do the same.

**Comment by DocMAX** [comment]
I can't get it to work. No controller visible. My command:

`x11docker --xorg --vt 7 --pulseaudio --wm none --gpu --homedir /opt/kodi/docker/ -- -v /opt/kodi/media:/media:ro --device=/dev/input/by-id/usb-©Microsoft_Xbox_360_Wireless_Receiver_for_Windows_FEE576B0-event-joystick:/dev/input/by-id/usb-©Microsoft_Xbox_360_Wireless_Receiver_for_Windows_FEE576B0-event-joystick -- erichough/kodi`

**Comment by ehough** [comment]
I think the image is missing a package: `kodi-peripheral-joystick`

Could you try installing that with `apt-get update && apt-get install kodi-peripheral-joystick`? Alternatively, [here's](https://pastebin.com/raw/JcUnztiz) a `Dockerfile` that I'm testing for a future release that you could build and test locally.

I'm hoping to spend some time testing this weekend.

**Comment by mviereck** [comment]
Here someone set up a gamepad to work with x11docker: https://github.com/mviereck/x11docker/issues/89

**Comment by DocMAX** [comment]
It's working now with `kodi-peripheral-joystick`
My commandline looks like this:

`x11docker --xorg --vt 7 --pulseaudio --wm none --gpu --homedir /opt/kodi/docker/ -- -v /opt/kodi/media:/media:ro --privileged --device=/dev/input/by-id/usb-©Microsoft_Xbox_360_Wireless_Receiver_for_Windows_FEE576B0-event-joystick -- docmax/kodi`

**Comment by mviereck** [comment]
> It's working now with `kodi-peripheral-joystick`

Good to know.
> It's not working without "--privileged"

If you use `--privileged`, you should not need `--device=/dev/input/by-id/usb-©Microsoft_Xbox_360_Wireless_Receiver_for_Windows_FEE576B0-event-joystick` because `--privileged` already provides _all_ devices to the container.

However, `--privileged` breaks container isolation. A more specific solution is desirable.

Could you try with `--sharedir /run/udev/data:ro --cap-default` instead of `--privileged`?

`x11docker --xorg --vt 7 --pulseaudio --wm none --gpu --homedir /opt/kodi/docker/ --sharedir /run/udev/data:ro --cap-default -- -v /opt/kodi/media:/media:ro --device=/dev/input/by-id/usb-©Microsoft_Xbox_360_Wireless_Receiver_for_Windows_FEE576B0-event-joystick -- docmax/kodi`

**Comment by DocMAX** [comment]
Tried this, doesn't work.

**Comment by dafrenchyman** [comment]
You'll have to find which js* is your controller, but I've been able pass it like this:
`... --device=/dev/input/js0 ...`
